# Generated by Django 4.1 on 2022-08-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_inventario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cliente_list',
            field=models.ManyToManyField(blank=True, related_name='empresa', to='factura.cliente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empleado_list',
            field=models.ManyToManyField(blank=True, related_name='empresa', to='factura.empleado'),
        ),
    ]
