# Generated by Django 4.1 on 2022-08-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_alter_producto_preciounitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.cliente'),
        ),
    ]
