# Generated by Django 4.1 on 2022-08-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_factura_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto_iva',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.FloatField(blank=True),
        ),
    ]
