# Generated by Django 4.1 on 2022-08-07 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_remove_factura_id_alter_factura_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.factura'),
        ),
    ]
