# Generated by Django 4.1 on 2022-08-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_detallefactura_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='en_stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
