# Generated by Django 4.1 on 2022-08-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0010_remove_producto_preciounitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='en_stock',
        ),
    ]
