# Generated by Django 4.1 on 2022-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0011_remove_inventario_en_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='valorTotal',
            field=models.FloatField(blank=True),
        ),
    ]
