# Generated by Django 4.1 on 2022-08-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0012_alter_detallefactura_valortotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='valorTotal',
        ),
    ]
