# Generated by Django 4.1 on 2022-08-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0014_remove_detallefactura_factura_factura_detalle_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='detalle_list',
        ),
        migrations.AddField(
            model_name='factura',
            name='detalle_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='factura', to='factura.detallefactura'),
        ),
    ]
