# Generated by Django 4.1 on 2022-08-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0017_remove_factura_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='monto_iva',
        ),
    ]
