# Generated by Django 4.1 on 2022-08-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0019_remove_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
