# Generated by Django 4.1 on 2022-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0021_factura_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='montoiva',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_total',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
