# Generated by Django 4.1 on 2022-08-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0022_factura_montoiva_factura_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='sub_total',
        ),
    ]
