# Generated by Django 4.1 on 2022-08-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0026_alter_factura_montoiva_alter_factura_sub_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='montoiva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='valor_total',
        ),
    ]
