# Generated by Django 4.1 on 2022-08-12 22:25

from django.db import migrations, models
import factura.models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0031_alter_factura_montoiva_alter_factura_sub_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='sub_total',
            field=models.FloatField(default=factura.models.Factura.subtotal, editable=False),
        ),
    ]
