/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import model.Empleado;
import model.Empresa;

/**
 *
 * @author Usuario
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        Empleado empleado=new Empleado();
        InterfazInicioSesion interfazInicioSesion=new InterfazInicioSesion();
        empleado.mostrarEmpleado("1708575467");
        txtIDempleado.setText(empleado.getIdEmpleado());
        NombreEmpleado.setText(empleado.getNombre());
        

    }
    
    public Empleado ObtenerDatosEmpleado(){
        Empleado empleado = new Empleado("15441212");
        empleado.setIdEmpleado(txtIDempleado.getText());
        return empleado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelOpciones = new javax.swing.JPanel();
        DatosEmpleado = new javax.swing.JPanel();
        NombreEmpleado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIDempleado = new javax.swing.JTextField();
        panImagen2 = new gui.PanImagen();
        btnDatosEmpresa = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnFacturas1 = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanelDetalles = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panImagen3 = new gui.PanImagen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelOpciones.setBackground(new java.awt.Color(3, 48, 90));
        PanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreEmpleado.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        NombreEmpleado.setText("NombreEmpleado");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Id.Empleado:");

        txtIDempleado.setEditable(false);
        txtIDempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDempleadoActionPerformed(evt);
            }
        });

        panImagen2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\Uusario.png")); // NOI18N

        javax.swing.GroupLayout panImagen2Layout = new javax.swing.GroupLayout(panImagen2);
        panImagen2.setLayout(panImagen2Layout);
        panImagen2Layout.setHorizontalGroup(
            panImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panImagen2Layout.setVerticalGroup(
            panImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DatosEmpleadoLayout = new javax.swing.GroupLayout(DatosEmpleado);
        DatosEmpleado.setLayout(DatosEmpleadoLayout);
        DatosEmpleadoLayout.setHorizontalGroup(
            DatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosEmpleadoLayout.createSequentialGroup()
                .addGroup(DatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosEmpleadoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(NombreEmpleado))
                    .addGroup(DatosEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatosEmpleadoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(panImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        DatosEmpleadoLayout.setVerticalGroup(
            DatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelOpciones.add(DatosEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 170));

        btnDatosEmpresa.setBackground(new java.awt.Color(153, 153, 153));
        btnDatosEmpresa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnDatosEmpresa.setText("Datos Empresa");
        btnDatosEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatosEmpresaMouseClicked(evt);
            }
        });
        btnDatosEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosEmpresaActionPerformed(evt);
            }
        });
        PanelOpciones.add(btnDatosEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 50));

        btnInventario.setBackground(new java.awt.Color(153, 153, 153));
        btnInventario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventarioMouseClicked(evt);
            }
        });
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        PanelOpciones.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 230, 50));

        btnClientes.setBackground(new java.awt.Color(153, 153, 153));
        btnClientes.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        PanelOpciones.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 230, 50));

        btnFacturas1.setBackground(new java.awt.Color(153, 153, 153));
        btnFacturas1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnFacturas1.setText("Facturas");
        btnFacturas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturas1MouseClicked(evt);
            }
        });
        btnFacturas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturas1ActionPerformed(evt);
            }
        });
        PanelOpciones.add(btnFacturas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 230, 50));

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        PanelOpciones.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Soporte");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        PanelOpciones.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 230, 50));

        PanelPrincipal.add(PanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 600));

        PanelDetalles.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 3, 48)); // NOI18N
        jLabel2.setText("Sistema Facturacion");

        panImagen3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\pngtree-letter-l-logo-branding-business-image_1124200(1)(2).jpg")); // NOI18N

        javax.swing.GroupLayout panImagen3Layout = new javax.swing.GroupLayout(panImagen3);
        panImagen3.setLayout(panImagen3Layout);
        panImagen3Layout.setHorizontalGroup(
            panImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        panImagen3Layout.setVerticalGroup(
            panImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelDetallesLayout = new javax.swing.GroupLayout(PanelDetalles);
        PanelDetalles.setLayout(PanelDetallesLayout);
        PanelDetallesLayout.setHorizontalGroup(
            PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetallesLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetallesLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetallesLayout.createSequentialGroup()
                        .addComponent(panImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        PanelDetallesLayout.setVerticalGroup(
            PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetallesLayout.createSequentialGroup()
                .addGap(0, 190, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        PanelPrincipal.add(PanelDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 720, 600));

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatosEmpresaMouseClicked
        // TODO add your handling code here:
        PanelEmpresa panelEmpresa=new PanelEmpresa();
        panelEmpresa.setSize(700,600);
        Empresa empresa=new Empresa();
        
        
        
      

        PanelDetalles.removeAll();
        PanelDetalles.add(panelEmpresa, BorderLayout.CENTER);
        PanelDetalles.revalidate();
        PanelDetalles.repaint();
    }//GEN-LAST:event_btnDatosEmpresaMouseClicked

    private void btnDatosEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosEmpresaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDatosEmpresaActionPerformed

    private void btnInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseClicked
        // TODO add your handling code here:
        PanelInventario panelInventario=new PanelInventario();
        panelInventario.setSize(700,600);

        PanelDetalles.removeAll();
        PanelDetalles.add(panelInventario, BorderLayout.CENTER);
        PanelDetalles.revalidate();
        PanelDetalles.repaint();
    }//GEN-LAST:event_btnInventarioMouseClicked

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        // TODO add your handling code here:
        PanelCliente panelCliente=new PanelCliente();
        panelCliente.setSize(700, 600);

        PanelDetalles.removeAll();
        PanelDetalles.add(panelCliente, BorderLayout.CENTER);
        PanelDetalles.revalidate();
        PanelDetalles.repaint();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFacturas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturas1MouseClicked
        // TODO add your handling code here:
        PanelFactura panelFactura=new PanelFactura();
        panelFactura.setSize(700, 600);

        PanelDetalles.removeAll();
        PanelDetalles.add(panelFactura, BorderLayout.CENTER);
        PanelDetalles.revalidate();
        PanelDetalles.repaint();
    }//GEN-LAST:event_btnFacturas1MouseClicked

    private void btnFacturas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturas1ActionPerformed

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        // TODO add your handling code here:
        int respuesta=JOptionPane.showConfirmDialog(this, "¿Esta seguro que quiere cerrar sesion?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(respuesta==JOptionPane.YES_OPTION){
            dispose();
            InterfazInicioSesion interfazInicioSesion=new InterfazInicioSesion();
            interfazInicioSesion.setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        PanelSoporte panelSoporte=new PanelSoporte();
        panelSoporte.setSize(700, 600);

        PanelDetalles.removeAll();
        PanelDetalles.add(panelSoporte, BorderLayout.CENTER);
        PanelDetalles.revalidate();
        PanelDetalles.repaint();
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtIDempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDempleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosEmpleado;
    private javax.swing.JLabel NombreEmpleado;
    private javax.swing.JPanel PanelDetalles;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDatosEmpresa;
    private javax.swing.JButton btnFacturas1;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private gui.PanImagen panImagen2;
    private gui.PanImagen panImagen3;
    private javax.swing.JTextField txtIDempleado;
    // End of variables declaration//GEN-END:variables
}
