/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.BorderLayout;

/**
 *
 * @author Usuario
 */
public class PanelInterfaz extends javax.swing.JPanel {

    /**
     * Creates new form PanelInterfaz
     */
    public PanelInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelOpciones = new javax.swing.JPanel();
        DatosEmpleado = new javax.swing.JPanel();
        NombreEmpleado = new javax.swing.JLabel();
        btnFacturas = new javax.swing.JButton();
        btnDatosEmpresa = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        PanelDetalles = new javax.swing.JPanel();

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelOpciones.setBackground(new java.awt.Color(0, 102, 102));
        PanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreEmpleado.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        NombreEmpleado.setText("NombreEmpleado");

        javax.swing.GroupLayout DatosEmpleadoLayout = new javax.swing.GroupLayout(DatosEmpleado);
        DatosEmpleado.setLayout(DatosEmpleadoLayout);
        DatosEmpleadoLayout.setHorizontalGroup(
            DatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosEmpleadoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(NombreEmpleado)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        DatosEmpleadoLayout.setVerticalGroup(
            DatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreEmpleado)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        PanelOpciones.add(DatosEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 140));

        btnFacturas.setBackground(new java.awt.Color(0, 153, 153));
        btnFacturas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnFacturas.setText("Facturas");
        btnFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturasMouseClicked(evt);
            }
        });
        btnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasActionPerformed(evt);
            }
        });
        PanelOpciones.add(btnFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 230, 50));

        btnDatosEmpresa.setBackground(new java.awt.Color(0, 153, 153));
        btnDatosEmpresa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnDatosEmpresa.setText("Datos Empresa");
        btnDatosEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosEmpresaActionPerformed(evt);
            }
        });
        PanelOpciones.add(btnDatosEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 230, 50));

        btnInventario.setBackground(new java.awt.Color(0, 153, 153));
        btnInventario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnInventario.setText("Invetario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        PanelOpciones.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 50));

        btnClientes.setBackground(new java.awt.Color(0, 153, 153));
        btnClientes.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        PanelOpciones.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 230, 50));

        PanelPrincipal.add(PanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 600));

        PanelDetalles.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout PanelDetallesLayout = new javax.swing.GroupLayout(PanelDetalles);
        PanelDetalles.setLayout(PanelDetallesLayout);
        PanelDetallesLayout.setHorizontalGroup(
            PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        PanelDetallesLayout.setVerticalGroup(
            PanelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        PanelPrincipal.add(PanelDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 720, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturasMouseClicked
        // TODO add your handling code here:
        PanelFactura panelFactura=new PanelFactura();
        panelFactura.setSize(700, 600);

        PanelDetalles.removeAll();
        PanelDetalles.add(panelFactura, BorderLayout.CENTER);
        PanelDetalles.revalidate();
        PanelDetalles.repaint();
    }//GEN-LAST:event_btnFacturasMouseClicked

    private void btnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturasActionPerformed

    private void btnDatosEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatosEmpresaActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        // TODO add your handling code here:
        PanelCliente panelCliente=new PanelCliente();
        panelCliente.setSize(700, 600);

        PanelDetalles.removeAll();
        PanelDetalles.add(panelCliente, BorderLayout.CENTER);
        PanelDetalles.revalidate();
        PanelDetalles.repaint();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosEmpleado;
    private javax.swing.JLabel NombreEmpleado;
    private javax.swing.JPanel PanelDetalles;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDatosEmpresa;
    private javax.swing.JButton btnFacturas;
    private javax.swing.JButton btnInventario;
    // End of variables declaration//GEN-END:variables
}
